---
name: "Terraform Module PR Open"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: spilliams/workflow-testing/.github/workflows/reusable-terraform-module-changelog.yml@main
    permissions:
      contents: read
    with:
      compare_from: ${{ github.base_ref }}
      compare_to: ${{ github.head_ref }}
      release_module_versions: false
    secrets:
      PAT_WORKFLOW_WRITE: ${{ secrets.TAG_RELEASE_PAT }}
